### ISSUE TITLE
OpenStack HA Bundle

### ISSUE THREAD

**Issue by josiasmontag** [openstack-charmers/openstack-bundles#1]
It would be awesome if someone could port [this OpenStack HA configuration](https://wiki.ubuntu.com/ServerTeam/OpenStackHA) to a Juju bundle. Ideally using much less than 28 physical nodes by replacing some of them with LXC containers. Thanks in advance :)

**Comment by javacruft** [comment]
I agree that would be good; I think we can produce a bundle for this, however there is one piece that is awkward in that the charms need to know the virtual IP's for HA services, which will most likely be specific on a per-deployment basis.

I guess that could be poked in after deploying a bundle with those pieces missing.

**Comment by ryan-beisner** [comment]
Bugs in the bundle file can be raised here:  https://bugs.launchpad.net/openstack-bundles/+filebug
For q & a, please see:  https://docs.openstack.org/charm-guide/latest/find-us.html
