### ISSUE TITLE
README doesn't show how to create a flavor

### ISSUE THREAD

**Issue by dannf** [openstack-charmers/openstack-bundles#11]
The "Booting an instance" section of README.md provides an example of booting an instance using the m1.small flavor. However, I found that after deploying newton, no pre-existing flavors exist. I gather from a comment in charm-nova-compute/tests/basic_deployment.py that this is by-design starting with newton. However, if that is the case, then we should probably document how to create a flavor prior to launching a  guest that requires it.

**Comment by ryan-beisner** [comment]
I'm not sure where we would draw the line, of the many post-deployment cloud configuration tasks that one needs to do.  Other similar things:  create a user, create a tenant, create a neutron router, define a subnet, etc.  I'd lean toward not attempting to document how to create a flavor, as it is already well-documented.

I say that, with full agreement that it was a bit of a surprise going from M -> N, not having the default flavors.

http://docs.openstack.org/admin-guide/cli-manage-flavors.html

**Comment by ryan-beisner** [comment]
FYI, I've raised the following upstream documentation update:

https://review.openstack.org/#/c/416330/

**Comment by dannf** [comment]
On Tue, Jan 03, 2017 at 11:29:27AM -0800, Ryan Beisner wrote:
> FYI, I've raised the following upstream documentation update:
> 
> https://review.openstack.org/#/c/416330/

Thanks!

**Comment by dannf** [comment]
On Tue, Jan 03, 2017 at 11:00:49AM -0800, Ryan Beisner wrote:
> I'm not sure where we would draw the line, of the many
> post-deployment cloud configuration tasks that one needs to do.
> Other similar things:  create a user, create a tenant, create a
> neutron router, define a subnet, etc.  I'd lean toward not
> attempting to document how to create a flavor, as it is already
> well-documented.

I'm not sure where to draw a line either. However, my concern here is that
the bundle documentation does have a section called "Ensuring it's
working" with a few steps to get up to a booting instance. Starting
with Newton, that section is incomplete and the "Booting an instance"
step will fail. I've submitted a PR to that should be sufficient for
getting that working again.

  -dann

> 
> I say that, with full agreement that it was a bit of a surprise going from M -> N, not having the default flavors.
> 
> http://docs.openstack.org/admin-guide/cli-manage-flavors.html
> 
>

**Comment by ryan-beisner** [comment]
@dannf Perfect, thank you.
