### ISSUE TITLE
LBAASv2 not working (Could not load neutron_lbaas.drivers.haproxy.namespace_driver.HaproxyNSDriver)

### ISSUE THREAD

**Issue by BlackDex** [openstack-charmers/openstack-bundles#13]
Hello there,

I'm trying to enable LBAASv2. This option didn't got visible in the Horizon Dashboard after enabling this option. After some research i found that the neutron-lbaasv2-agent is spitting out some errors.

> 2017-01-03 21:00:51.153 6271 INFO neutron.common.config [-] Logging enabled!
> 2017-01-03 21:00:51.153 6271 INFO neutron.common.config [-] /usr/bin/neutron-lbaasv2-agent version 9.0.0
> 2017-01-03 21:00:51.153 6271 DEBUG neutron.common.config [-] command line: /usr/bin/neutron-lbaasv2-agent --config-file=/etc/neutron/neutron.conf --config-file=/etc/neutron/lbaas_agent.ini --log-file=/var/log/neutron/neutron-lbaasv2-agent.log setup_logging /usr/lib/python2.7/dist-packages/neutron/common/config.py:10
> 7
> 2017-01-03 21:00:51.154 6271 WARNING stevedore.named [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] Could not load neutron_lbaas.drivers.haproxy.namespace_driver.HaproxyNSDriver
> 2017-01-03 21:00:51.234 6271 WARNING stevedore.named [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] Could not load neutron.agent.linux.interface.OVSInterfaceDriver
> 2017-01-03 21:00:51.235 6271 DEBUG oslo_concurrency.lockutils [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] Acquired semaphore "singleton_lock" lock /usr/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:215
> 2017-01-03 21:00:51.236 6271 DEBUG oslo_concurrency.lockutils [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] Releasing semaphore "singleton_lock" lock /usr/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:228
> 2017-01-03 21:00:51.236 6271 DEBUG oslo_service.service [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] Full set of CONF: _wait_for_exit_or_signal /usr/lib/python2.7/dist-packages/oslo_service/service.py:302
> 2017-01-03 21:00:51.237 6271 DEBUG oslo_service.service [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] ******************************************************************************** log_opt_values /usr/lib/python2.7/dist-packages/oslo_config/cfg.py:2604
> 2017-01-03 21:00:51.237 6271 DEBUG oslo_service.service [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] Configuration options gathered from: log_opt_values /usr/lib/python2.7/dist-packages/oslo_config/cfg.py:2605
> 2017-01-03 21:00:51.238 6271 DEBUG oslo_service.service [req-3f38b24c-8162-4297-a899-a051ce9dbb1f - - - - -] command line args: ['--config-file=/etc/neutron/neutron.conf', '--config-file=/etc/neutron/lbaas_agent.ini', '--log-file=/var/log/neutron/neutron-lbaasv2-agent.log'] log_opt_values /usr/lib/python2.7/dist-pac
> kages/oslo_config/cfg.py:2606

I have tried to reinstall the packages, re-run the install hook, config hook etc.. nothing seemed to work to fix this issue.

Any help would be nice!
Using Ubuntu 16.04, neutron-gateway on a physical node neutron-api in a LXD container.
OpenStack Newton charms.

**Comment by BlackDex** [comment]
I had some more problems with deploying this bundle due to some network configuration changes.
Maybe it had to do something with this. I'm currently re-deploying the envirionment.

Ill update this ticket when i have re-deployed everything and tested it all.

Thx.

**Comment by BlackDex** [comment]
Oke, this still is an issue, reinstall didn't solved this problem.

**Comment by ryan-beisner** [comment]
Please track the following Launchpad bug in lieu of this GH issue.  Further triage and updates will occur there:

https://bugs.launchpad.net/charms/+source/neutron-gateway/+bug/1658105
