### ISSUE TITLE
README.md doesn't state some mandatory settings

### ISSUE THREAD

**Issue by BlackDex** [openstack-charmers/openstack-bundles#14]
When using the bundle as-is there could be some problems when scaling mysql/percona-cluster and the ceph deployment.

For ceph-mon you need to set the **monitor-secret** and **fsid**.
For percona-cluster you need to set **sst-password** and **root-password**.
Also the **min-cluster-size** should be set if this app/unit is going to be clustered. Else every unit is going to bootstrap-pxc on its own it seems.

Thx for all the great work!
BlackDex

**Comment by ryan-beisner** [comment]
@BlackDex  Which bundle are you using?  (openstack-base, openstack-telemetry, etc.)   These two bundles are non-HA, non-clustered examples.

Indeed, for more advanced use cases, such as HA, this, and a lot of other options need to be carefully-considered and adjusted.  It is not the goal of the base and telemetry bundles to illustrate that more-advanced use case.

**Comment by ryan-beisner** [comment]
@BlackDex For reference, there is a separate issue which is requesting that HA example bundles be added to this repo and subsequently to the charm store.  See issue #1.

**Comment by BlackDex** [comment]
@ryan-beisner I understand that for the percona part, but the ceph-mon needs those values if i'm correct. It failed me when i didn't provided monitor-secret and fsid.

For percona i understand that that is something you have to check for your self if you want to HA that feature.
So atleast ceph-mon would be greate if that will be added, unless it is generated automatically, but that is not stated at the ceph-mon charm, it states those values are mandatory.

**Comment by ryan-beisner** [comment]
@BlackDex 
The charm will generate an fsid and/or a monitor-secret if not provided [1], as of the 16.04 Stable OpenStack Charms release.  It looks like the config.yaml description is out of date.  I've raised a LP charm bug [2] against ceph-mon to track the need to update that help string.  Thanks again :-)

[1] https://github.com/openstack/charm-ceph-mon/commit/ce4fe7a0
[2] https://bugs.launchpad.net/charms/+source/ceph-mon/+bug/1661737
