### ISSUE TITLE
cinder in LXD/LXC Container doesn't support NFS mount

### ISSUE THREAD

**Issue by BlackDex** [openstack-charmers/openstack-bundles#15]
Hello there,

When using cinder within an LXD or LXC Container it isn't possible to mount an NFS share.
This is blocked by Apparmor.

**Comment by ryan-beisner** [comment]
Please raise this issue against the cinder charm, as it's not an issue with the construct of the bundle itself.  Be sure to include error messages related to the issue, as well as any customization to the bundle and the process by which NFS shares are being added.  Thank you.
https://bugs.launchpad.net/charms/+source/cinder/+filebug

**Comment by BlackDex** [comment]
Bug reported
https://bugs.launchpad.net/charms/+source/cinder/+bug/1661636
