### ISSUE TITLE
Openstack Telemetry has a bad mongodb series reference

### ISSUE THREAD

**Issue by patriziobassi** [openstack-charmers/openstack-bundles#16]
Hi,

trying to deploy 
# juju deploy cs:bundle/openstack-telemetry-41

i get an error message: cannot add unit for application "mongodb": adding new machine to host unit "mongodb/0"

infact the charm carries
    charm: cs:trusty/mongodb-33

and no xenial series seems available, this blocks deploy

**Comment by javacruft** [comment]
The output of:

```juju status --format=yaml mongodb```

and any information from the machine-0.log on the controller unit would be useful to dig in on this.

We should have an updated mongodb charm for xenial soon, but the current use of trusty should also DTRT for the interim
