### ISSUE TITLE
Juju-2.0b9 can't deploy LXC containers

### ISSUE THREAD

**Issue by juan-vg** [openstack-charmers/openstack-bundles#2]
LXC containers are not supported since Juju-2.0b9

All deployments involving LXC containers must be adapted in order to use LXD containers
(same notation as LXC,    lxc:0 ---> lxd:0)

**Comment by javacruft** [comment]
Juju grew automatic remapping of lxc -> lxd in a later beta (and for release) - the bundles have to be backwards compatible with 1.25.6 at the moment, so we'll leave things as 'lxc' for now.
