### ISSUE TITLE
issue on Ceph-Mon and Nova-Cloud-Controller

### ISSUE THREAD

**Issue by richardsith** [openstack-charmers/openstack-bundles#23]
Lab:

All environment Lab has been realised using Ubuntu 16.04.2 LTS:
1 VM for MAAS (memory: 8GB, CPU: 1, HDD: 500GB)upgraded with ppa stable;
1 VM for JUJU (memory: 8GB, CPU: 1, HDD: 500GB)upgraded with ppa stable;
4 VM for OPENSTACK (memory: 16GB, CPU: 1, HDD: 500GBx2);

after the deploy of bundle on my lab all nodes are started and they have changed their status in deployed, at the end of the task on juju I've received an issue on Ceph-Mon and Nova-Cloud-Controller. Look that 

[post on Ubuntu Ask](https://askubuntu.com/questions/913007/openstack-base-bundle-deployed-with-juju)

**Comment by richardsith** [comment]
any idea?

**Comment by ryan-beisner** [comment]
Issue closed on Ask forum.
