### ISSUE TITLE
neutron gateway: Status: error - hook failed: "config-changed"

### ISSUE THREAD

**Issue by richardsith** [openstack-charmers/openstack-bundles#28]
From 2 weeks each time I deploy openstack-lxd or openstack-base bundle from juju-gui receive the same issue on neutron-gateway

(Status: error - hook failed: "config-changed") 
![screen shot 2017-08-01 at 17 04 52](https://user-images.githubusercontent.com/9977215/28831975-91572372-76db-11e7-8694-a750e1a8d1f5.png)

why? before it works well.

**Comment by richardsith** [comment]
any idea? I try that again and the result was always the same.

**Comment by smohankarthik** [comment]
Hey , i had similar problem and i managed to fix the issue .
Refer to the link . Mi8 help you as well .

https://askubuntu.com/questions/346276/juju-error-hook-failed-config-changed

**Comment by richardsith** [comment]
the first command returns this issue:

> $: juju resolved --retry neutron-gateway/0
> ERROR flag provided but not defined: --retry

**Comment by smohankarthik** [comment]
Alright u can try it out without using the retry option. This definitely works.  
Versions get changed frequently & so does the options.

**Comment by richardsith** [comment]
this one the juju status during the command ([here](https://paste.ubuntu.com/25361578/).
while that one is after [here](https://paste.ubuntu.com/25361582/) same issue

**Comment by smohankarthik** [comment]
That's strange that hook failed error didn't change ..  
did you try the second part of the answer.. ?? the one with debug-hooks that should definitely work .. 
I tried it multiple times and it worked always.

**Comment by richardsith** [comment]
from here what I've to run 
![screen shot 2017-08-21 at 12 18 00](https://user-images.githubusercontent.com/9977215/29515016-e7866aca-866a-11e7-977a-cd54dc13eaca.png)

**Comment by richardsith** [comment]
whats happened after that command? [here is the juju status](https://paste.ubuntu.com/25361823/)
and on juju gui
![screen shot 2017-08-21 at 12 24 34](https://user-images.githubusercontent.com/9977215/29515212-ceb44160-866b-11e7-9b05-9c89bd33535e.png)

**Comment by smohankarthik** [comment]
When u debug-hooks into the node.
It will ssh and tmux you into the machine and u need to wait for the  config-changed to run. And you need to manually trigger the hook outside(from juju node) by running resolved command . Once the hook starts you can run the hook script manually, inspect its output or relation settings, or change what the hook does, interactively. See the status after few mins ..  
This steps are mentioned in the stackoverflow link.

**Comment by richardsith** [comment]
@smohankarthik At moment I've not any type of issue about that. Your suggest has been the solution to my problem.

Thanks

**Comment by smohankarthik** [comment]
Hi @richardsith , 
I have a few queries and i raised issues also in github but unfortunately didnt manage to get a reply, so i thought of asking you.  
I see that you also use openstack-base juju charm bundle and also deployed openstack with it. Just wanted to know how stable is it. Bcos sometimes i see that services are in error state (because of hook issues) , although by using workarounds it does work but it later goes back into  error state more oftenly. Do you also encounter such issues. .?? 
Curious for a reply. :) 
 
Thanks in advance..!!
Mohan

**Comment by richardsith** [comment]
Hi @smohankarthik, I'm using that combination of Maas, Juju, Landscape and Openstack in a lab environment not in production, at moment (my opinion) I 'm not feel sure to implement that as a complete cloud solution for our customer. I think that is not ready yet as enterprise solution, as you said, some time there are errors state on charms that we don't know how to resolve that. 
If I can suggest you a think, for a internal lab solution where to study the product and running the tests it's perfect, but I'm waiting to implement that in production environment.

**Comment by smohankarthik** [comment]
Thanks @richardsith . I know its pretty unstable for my env. I am using Maas, Juju and Openstack-base .  
On ur experience wid dis so far. What would be the best way for achieving it .? Will Openstack-Autopilot work better than the openstack-base .? I saw the Openstack autopilot have at least support from ubuntu and dey are promoting for production env.
They also  have something called bootstack for  deploying and maintaining  openstack.

**Comment by richardsith** [comment]
@smohankarthik I'm using both solution and Autopilot allows you  to have a good env without make too configuration. Consider that you can implement that using 2 way (production, and lab): 1 - y must have minimal 7 host or vm (1 fox Maas, 1 for Juju, 1 for Landscape 'n 4 for Openstack; 2- can install that on a only 1 host.

**Comment by smohankarthik** [comment]
Hi @richardsith  , I have deployed Openstack Autopilot on my servers successfully. I have a couple of problems.
1. When i try to spin up a VM. I am getting error saying **No Valid Host was found. There are not enough hosts available** . I get this error when i opt for volume creation while launching an instance. The same thing when I try with out  choosing the volume its gets getting created with out any issue.

2. How do i ssh into the VM/Containers after deploying openstack. when i do juju status . I get nly landscape,HAProxy,postgresql, rabbitmq . Any idea on how to ssh into nova or neutron etc... 

I am kind of stuck. Hope you can help me out in this issue.
Thanks in advance..!!
