### ISSUE TITLE
Unable to locate package  python-glanceclient

### ISSUE THREAD

**Issue by emsi** [openstack-charmers/openstack-bundles#3]
There's no such thing as `python-glanceclient` package per default xenial configuration.

p.s. the Openstack documentation links are broken.

**Comment by javacruft** [comment]
This is puzzling, as I see a valid install candidate on a fresh Xenial install:

# apt-cache policy python-glanceclient
python-glanceclient:
  Installed: (none)
  Candidate: 1:2.0.0-2ubuntu0.16.04.1
  Version table:
     1:2.0.0-2ubuntu0.16.04.1 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     1:2.0.0-2 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by ryan-beisner** [comment]
Re-confirmed a fresh Xenial instance has python-glanceclient available.  Please re-open if there is a case where this can be reproduced.  Thank you.
