### ISSUE TITLE
Questions about the openstack-base bundle

### ISSUE THREAD

**Issue by alogracia** [openstack-charmers/openstack-bundles#30]
Hello,

I have some questions about the openstack-base bundle, I hope this is a good place to ask (i couldn't find another one):
- Where is the Openstack API deployed, in the network of Openstack services (eth0) or in the public traffic network (eth1)?
- In case the answer is in Openstack services network, is it possible to move it to the public network modifying the charm? We need to use the API from external elements
- Is it possible to switch off the provisioning system (juju+MaaS) and keep Openstack operative, everything working?

Thanks
Antonio

**Comment by javacruft** [comment]
Hi

a) API's should be accessible via the primary network interface on each machine
b) The charms support network spaces in Juju using bindings, so its possible to bind public, internal and admin endpoints to different underlying networks - however that does take some more configuration in MAAS prior to deployment.
c) Not recommended - what's your rationale for turning then off?

**Comment by javacruft** [comment]
(you can come ask questions in #openstack-charms on Freenode IRC as well)

**Comment by alogracia** [comment]
Hi, thanks for your answers. Some more questions:
a) That's the network of Openstack services (eth0), right? I understand that network is not reachable from outside
b) What MAAS configuration? Is there any documentation about it?
c) The rationale is that Openstack services should be not dependant on the provision system used to deploy Openstack to make the system more robust and avoid possible bottlenecks.

**Comment by ryan-beisner** [comment]
For Q & A, please use the mailing lists or irc channels.

To raise a bug against the bundle files, see:
https://bugs.launchpad.net/openstack-bundles/+filebug

Docs follow:
https://docs.openstack.org/charm-deployment-guide/latest/
https://maas.io

Thank you.
