### ISSUE TITLE
Openstack services gets into hook issues 

### ISSUE THREAD

**Issue by smohankarthik** [openstack-charmers/openstack-bundles#33]
Hello,

I hope this is the place to ask a query regrading Openstack-base bundle.

I deployed Openstack successfully using Juju Charm over MaaS servers. Openstack is up and running but after sometime, some of the **Units lands up into error/blocked state**(_i.e charm hook issues regarding to update-status and config-changed_) but after doing workarounds(_juju resolved & debug-hooks_) it does work. And the process repeats after sometime.

Is there any thing that you guys feel that has been missed out because of which i come across this charm hook issues frequently..?
Any lead to this would be really helpful. 

Thanks in advance..!!

**Comment by szeestraten** [comment]
Hey @smohankarthik, if you don't get any action here I suggest asking in #openstack-charms IRC channel on Freenode. Also if you run into a bug with an OpenStack charm, look it up on [jujucharms.com](https://jujucharms.com/u/openstack-charmers/) and hit the _Submit a bug_.

**Comment by smohankarthik** [comment]
Thanks @szeestraten  I tried asking over freenode , but didnt get any reply .

**Comment by szeestraten** [comment]
@smohankarthik No problem. The team is pretty spread out time zone wise so you might also have better luck getting in touch via other means such as mailing lists. See https://docs.openstack.org/charm-guide/latest/find-us.html
