### ISSUE TITLE
Sometime nova-cloud-controller creates its own zone 'internal'

### ISSUE THREAD

**Issue by ryanmickler** [openstack-charmers/openstack-bundles#37]
I've been deploying openstack base a few times, changing just a few of the minor settings, and i have noticed that sometimes i get 
`cinder/0*                 blocked   idle   1/lxd/1  192.168.128.96   8776/tcp           Services not running that should be: cinder-volume`
in `juju status`, but everything has completely deployed. However, things seem to run just fine when this happens (as far as i can tell?)

Now, i've been doing some digging, and i find that in horizon, i see that the lxd container that nova-cloud-controller has been put on is 'internal', while the rest of the hosts are in 'nova'. Could this be the cause of my error? I dont believe i have changed anything to do with zones in the bundle.yaml. I see that nova.conf has a `internal_service_availability_zone = internal` setting, so i suspect this isnt the cause.

thanks for any help.

**Comment by ryan-beisner** [comment]
Bugs in the bundle file can be raised here:  https://bugs.launchpad.net/openstack-bundles/+filebug

For q & a, please see:  https://docs.openstack.org/charm-guide/latest/find-us.html
