### ISSUE TITLE
qemu-kvm service disabled after reboot

### ISSUE THREAD

**Issue by marosg42** [openstack-charmers/openstack-bundles#38]
When I reboot nodes, all services come up except three nova-compute services. All three report blocked in juju status, with reason like "expected service qemu-kvm not available".
I logged on to nova-compute and the service is disabled. When I enable it on all three nodes, all is ok.

**Comment by McL0v1n** [comment]
I initially solved this by going to each compute node and typing:

`sudo systemctl enable qemu.kvm.service`

But now it doesnt do that anymore.

**Comment by ryan-beisner** [comment]
Can you please raise a bug against the nova-compute charm and include relevant log files?  Thank you.
https://bugs.launchpad.net/charm-nova-compute/+filebug
