### ISSUE TITLE
Ubuntu 16 Xenial Mitaka, Neutron Gateway - missing vpnaas setup

### ISSUE THREAD

**Issue by wmphang** [openstack-charmers/openstack-bundles#39]
Hi,
 I have try out the juju openstack Mitaka setup. Installation is ok, however I am missing vpnaas setup on Neutron-gateway. The neutron-vpn-agent is not install on the neutron gateway and the vpn_agent.ini configuration is using Openswan and not StrongSwan driver. Ubuntu 16 default package does not have openswan. 
Am I missing some juju charms here?

Thanks

**Comment by ryan-beisner** [comment]
Can you please paste the juju bundle that you're using, and a juju status?

**Comment by wmphang** [comment]
Hi @ryan-beisner 
 I'm using the following charm for testing
- cs:neutron-gateway-240
- cs:neutron-api-252

Looking at the charm hooks, for mitaka portion does not handle the vpnaas and lbaasv2 installation.
I'm currently experimenting the hooks to include the both module for mikata.

Is there any more updated charm for neutron?

Thanks

**Comment by javacruft** [comment]
vpnaas was dropped from the charms a while back (I think the last release we supported it on was precise).  The project is also struggling for contributors within the OpenStack ecosystem so I'd not proposed re-adding support any time soon.
